//
// Test Bench Module Tom_Dan_2_0_lib.apb_tester.apb_tester
//
// Created:
//          by - danbenam.UNKNOWN (L330W513)
//          at - 14:01:19 11/20/2021
//
// Generated by Mentor Graphics' HDL Designer(TM) 2019.2 (Build 5)
//
`resetall
`timescale 1ns/10ps
module apb_tester (clk,
                   pwrite,
                   psel,
                   penable,
                   Rd_Wr_Id
                  );

// Local declarations

parameter AMBA_WORD = 32;
parameter AMBA_ADDR_WIDTH = 20;
parameter DATA_WIDTH = 8;


output clk;
output pwrite;
output psel;
output penable;
input  Rd_Wr_Id;

logic       clk;
logic       pwrite;
logic       psel;
logic       penable;
logic [1:0] Rd_Wr_Id;


endmodule // apb_tester


