//
// Test Bench Module Tom_Dan_2_0_lib.control_unit_tester.control_unit_tester
//
// Created:
//          by - danbenam.UNKNOWN (L330W513)
//          at - 16:07:30 11/20/2021
//
// Generated by Mentor Graphics' HDL Designer(TM) 2019.2 (Build 5)
//
`resetall
`timescale 1ns/10ps
module control_unit_tester (CTRL,
                            operation_done,
                            FC_or_Dec,
                            En_or_Dec
                           );

// Local declarations

parameter AMBA_WORD = 32;
parameter AMBA_ADDR_WIDTH = 20;
parameter DATA_WIDTH = 32;


output CTRL;
input  operation_done;
input  FC_or_Dec;
input  En_or_Dec;

logic [AMBA_WORD - 1:0] CTRL;
logic                   operation_done;
logic                   FC_or_Dec;
logic                   En_or_Dec;


endmodule // control_unit_tester


