//
// Test Bench Module Tom_Dan_2_0_lib.decoder_tester.decoder_tester
//
// Created:
//          by - danbenam.UNKNOWN (L330W513)
//          at - 11:01:34 11/19/2021
//
// Generated by Mentor Graphics' HDL Designer(TM) 2019.2 (Build 5)
//
`resetall
`timescale 1ns/10ps
module decoder_tester (clk,
                       NoisyCodeWord,
                       Codeword_Width,
                       Decoded_Data,
                       NumOfErrors
                      );

// Local declarations

parameter AMBA_WORD = 32;
parameter AMBA_ADDR_WIDTH = 20;
parameter DATA_WIDTH = 32;


output clk;
output NoisyCodeWord;
output Codeword_Width;
input  Decoded_Data;
input  NumOfErrors;

logic                    clk;
logic [DATA_WIDTH - 1:0] NoisyCodeWord;
logic [1:0]              Codeword_Width;
logic [DATA_WIDTH - 1:0] Decoded_Data;
logic [1:0]              NumOfErrors;


endmodule // decoder_tester


