//
// Test Bench Module Tom_Dan_2_0_lib.ECC_ENC_DEC_tester.ECC_ENC_DEC_tester
//
// Created:
//          by - danbenam.UNKNOWN (L330W513)
//          at - 16:58:35 11/20/2021
//
// Generated by Mentor Graphics' HDL Designer(TM) 2019.2 (Build 5)
//
`resetall
`timescale 1ns/10ps
module ECC_ENC_DEC_tester (PADDR,
                           PENABLE,
                           PSEL,
                           PWDATA,
                           PWRITE,
                           clk,
                           arstn,
                           PRDATA,
                           data_out,
                           operation_done,
                           num_of_errors
                          );

// Local declarations

parameter AMBA_WORD = 32;
parameter AMBA_ADDR_WIDTH = 20;
parameter DATA_WIDTH = 32;


output PADDR;
output PENABLE;
output PSEL;
output PWDATA;
output PWRITE;
output clk;
output arstn;
input  PRDATA;
input  data_out;
input  operation_done;
input  num_of_errors;

logic [AMBA_WORD - 1:0]  PADDR;
logic                    PENABLE;
logic                    PSEL;
logic [AMBA_WORD - 1:0]  PWDATA;
logic                    PWRITE;
logic                    clk;
logic                    arstn;
logic [AMBA_WORD - 1:0]  PRDATA;
logic [DATA_WIDTH - 1:0] data_out;
logic                    operation_done;
logic                    num_of_errors;


endmodule // ECC_ENC_DEC_tester


