//
// Test Bench Module Tom_Dan_2_0_lib.encoder_tester.encoder_tester
//
// Created:
//          by - danbenam.UNKNOWN (L330W513)
//          at - 18:43:11 11/18/2021
//
// Generated by Mentor Graphics' HDL Designer(TM) 2019.2 (Build 5)
//
`resetall
`timescale 1ns/10ps
module encoder_tester (clk,
                       DATA_IN,
                       Codeword_Width,
                       EN_output
                      );

// Local declarations

parameter AMBA_WORD = 32;
parameter AMBA_ADDR_WIDTH = 20;
parameter DATA_WIDTH = 32;


output clk;
output DATA_IN;
output Codeword_Width;
input  EN_output;

logic                    clk;
logic [DATA_WIDTH - 1:0] DATA_IN;
logic [1:0]              Codeword_Width;
logic [DATA_WIDTH - 1:0] EN_output;


endmodule // encoder_tester


