//
// Test Bench Module Tom_Dan_2_0_lib.mat_mult_tb.mat_mult_tester
//
// Created:
//          by - danbenam.UNKNOWN (L330W513)
//          at - 15:16:56 11/19/2021
//
// Generated by Mentor Graphics' HDL Designer(TM) 2019.2 (Build 5)
//
`resetall
`timescale 1ns/10ps

module mat_mult_tb;

// Local declarations
parameter AMBA_WORD = 32;
parameter AMBA_ADDR_WIDTH = 20;
parameter DATA_WIDTH = 8;

// Internal signal declarations
logic [DATA_WIDTH - 1:0] NoisyCodeWord;
logic [1:0]              Codeword_Width;
logic [5:0]              column;


mat_mult #(32,20,8) U_0(
   .NoisyCodeWord  (NoisyCodeWord),
   .Codeword_Width (Codeword_Width),
   .column         (column)
);

mat_mult_tester #(32,20,8) U_1(
   .NoisyCodeWord  (NoisyCodeWord),
   .Codeword_Width (Codeword_Width),
   .column         (column)
);

endmodule // mat_mult_tb


