//
// Test Bench Module Tom_Dan_2_0_lib.noise_adder_tester.noise_adder_tester
//
// Created:
//          by - danbenam.UNKNOWN (L330W513)
//          at - 16:06:59 11/20/2021
//
// Generated by Mentor Graphics' HDL Designer(TM) 2019.2 (Build 5)
//
`resetall
`timescale 1ns/10ps
module noise_adder_tester (noise,
                           Encoded_data,
                           noisy_codeword
                          );

// Local declarations

parameter AMBA_WORD = 32;
parameter AMBA_ADDR_WIDTH = 20;
parameter DATA_WIDTH = 32;


output noise;
output Encoded_data;
input  noisy_codeword;

logic [AMBA_WORD - 1:0] noise;
logic [AMBA_WORD - 1:0] Encoded_data;
logic [AMBA_WORD - 1:0] noisy_codeword;


endmodule // noise_adder_tester


