//
// Test Bench Module Tom_Dan_2_0_lib.op_done_logic_tester.op_done_logic_tester
//
// Created:
//          by - kessoust.UNKNOWN (L330W513)
//          at - 15:33:26 12/10/2021
//
// Generated by Mentor Graphics' HDL Designer(TM) 2019.2 (Build 5)
//
`resetall
`timescale 1ns/10ps
module op_done_logic_tester (clk,
                             rst,
                             Rd_Wr_Id,
                             address,
                             operation_done
                            );

// Local declarations



output clk;
output rst;
output Rd_Wr_Id;
output address;
input  operation_done;

logic       clk;
logic       rst;
logic [1:0] Rd_Wr_Id;
logic [3:0] address;
logic       operation_done;


endmodule // op_done_logic_tester


