//
// Test Bench Module Tom_Dan_2_0_lib.control_unit_tb.control_unit_tester
//
// Created:
//          by - danbenam.UNKNOWN (L330W513)
//          at - 16:07:30 11/20/2021
//
// Generated by Mentor Graphics' HDL Designer(TM) 2019.2 (Build 5)
//
`resetall
`timescale 1ns/10ps

module control_unit_tb;

// Local declarations
parameter AMBA_WORD = 32;
parameter AMBA_ADDR_WIDTH = 20;
parameter DATA_WIDTH = 32;

// Internal signal declarations
logic [1:0] CTRL;
logic                   operation_done;
logic                   FC_or_Dec;
logic                   En_or_Dec;


control_unit #(32,20,32) U_0(
   .CTRL           (CTRL),
   .operation_done (operation_done),
   .FC_or_Dec      (FC_or_Dec),
   .En_or_Dec      (En_or_Dec)
);

control_unit_tester #(32,20,32) U_1(
   .CTRL           (CTRL),
   .operation_done (operation_done),
   .FC_or_Dec      (FC_or_Dec),
   .En_or_Dec      (En_or_Dec)
);









endmodule // control_unit_tb


