//
// Test Bench Module Tom_Dan_2_0_lib.mat_mult_2_tb.mat_mult_2_tester
//
// Created:
//          by - danbenam.UNKNOWN (L330W513)
//          at - 12:24:16 11/26/2021
//
// Generated by Mentor Graphics' HDL Designer(TM) 2019.2 (Build 5)
//
`resetall
`timescale 1ns/10ps

module mat_mult_2_tb;

// Local declarations
parameter DATA_WIDTH = 32;

// Internal signal declarations
logic [DATA_WIDTH - 1:0] NoisyCodeWord;
logic [1:0]              Codeword_Width;
logic [4:0]              column;


mat_mult_2 #(32) U_0(
   .NoisyCodeWord  (NoisyCodeWord),
   .Codeword_Width (Codeword_Width),
   .column         (column)
);

mat_mult_2_tester #(32) U_1(
   .NoisyCodeWord  (NoisyCodeWord),
   .Codeword_Width (Codeword_Width),
   .column         (column)
);

endmodule // mat_mult_2_tb


