//
// Test Bench Module Tom_Dan_2_0_lib.mux_H2_tb.mux_H2_tester
//
// Created:
//          by - danbenam.UNKNOWN (L330W513)
//          at - 17:06:39 11/19/2021
//
// Generated by Mentor Graphics' HDL Designer(TM) 2019.2 (Build 5)
//
`resetall
`timescale 1ns/10ps

module mux_H2_tb;

// Local declarations
parameter AMBA_WORD = 32;
parameter AMBA_ADDR_WIDTH = 20;
parameter DATA_WIDTH = 32;

// Internal signal declarations
logic                    clk;
logic [DATA_WIDTH - 1:0] NoisyCodeWord;
logic [1:0]              Codeword_Width;
logic [5:0]              column;
logic [DATA_WIDTH - 1:0] Decoded_Data;
logic [1:0]              NumOfErrors;


mux_H2 #(32,20,32) U_0(
   .clk            (clk),
   .NoisyCodeWord  (NoisyCodeWord),
   .Codeword_Width (Codeword_Width),
   .column         (column),
   .Decoded_Data   (Decoded_Data),
   .NumOfErrors    (NumOfErrors)
);

mux_H2_tester #(32,20,32) U_1(
   .clk            (clk),
   .NoisyCodeWord  (NoisyCodeWord),
   .Codeword_Width (Codeword_Width),
   .column         (column),
   .Decoded_Data   (Decoded_Data),
   .NumOfErrors    (NumOfErrors)
);

endmodule // mux_H2_tb


