//
// Test Bench Module Tom_Dan_2_0_lib.noise_adder_tb.noise_adder_tester
//
// Created:
//          by - danbenam.UNKNOWN (L330W513)
//          at - 16:06:59 11/20/2021
//
// Generated by Mentor Graphics' HDL Designer(TM) 2019.2 (Build 5)
//
`resetall
`timescale 1ns/10ps

module noise_adder_tb;

// Local declarations
parameter AMBA_WORD = 32;
parameter AMBA_ADDR_WIDTH = 20;
parameter DATA_WIDTH = 32;

// Internal signal declarations
logic [AMBA_WORD - 1:0] noise;
logic [AMBA_WORD - 1:0] Encoded_data;
logic [AMBA_WORD - 1:0] noisy_codeword;


noise_adder #(32,20,32) U_0(
   .noise          (noise),
   .Encoded_data   (Encoded_data),
   .noisy_codeword (noisy_codeword)
);

noise_adder_tester #(32,20,32) U_1(
   .noise          (noise),
   .Encoded_data   (Encoded_data),
   .noisy_codeword (noisy_codeword)
);

endmodule // noise_adder_tb


