executable_1: assignment3.o AdministrationPersonal.o Class.o Layer.o Manager.o Person.o Pupil.o School.o Secretary.o Teacher.o Tutor.o VecAnalyser.o Worker.o
	g++ assignment3.o AdministrationPersonal.o Class.o Layer.o Manager.o Person.o Pupil.o School.o Secretary.o Teacher.o Tutor.o VecAnalyser.o Worker.o -o executable_1

assignment3.o: assignment3.cpp
	g++ -c assignment3.cpp	

AdministrationPersonal.o: AdministrationPersonal.cpp
	g++ -c AdministrationPersonal.cpp

Class.o: Class.cpp
	g++ -c Class.cpp

Layer.o: Layer.cpp
	g++ -c Layer.cpp

Manager.o: Manager.cpp
	g++ -c Manager.cpp

Person.o: Person.cpp
	g++ -c Person.cpp

Pupil.o: Pupil.cpp
	g++ -c Pupil.cpp

School.o: School.cpp
	g++ -c School.cpp

Secretary.o: Secretary.cpp
	g++ -c Secretary.cpp

Teacher.o: Teacher.cpp
	g++ -c Teacher.cpp

Tutor.o: Tutor.cpp
	g++ -c Tutor.cpp

VecAnalyser.o: VecAnalyser.cpp
	g++ -c VecAnalyser.cpp

Worker.o: Worker.cpp
	g++ -c Worker.cpp

clean:
	rm *.o executable_1
